// Array.filter polyfill (MDN)
[].filter||(Array.prototype.filter=function(c,f){if(null==this)throw new TypeError;var b=Object(this),g=b.length>>>0;if("function"!=typeof c)throw new TypeError;for(var d=[],a=0;a<g;a++)if(a in b){var e=b[a];c.call(f,e,a,b)&&d.push(e)}return d});

// Array.map polyfill (MDN)
[].map||(Array.prototype.map=function(d,f){var g,e,a;if(null==this)throw new TypeError(" this is null or not defined");var b=Object(this),h=b.length>>>0;if("function"!==typeof d)throw new TypeError(d+" is not a function");f&&(g=f);e=Array(h);for(a=0;a<h;){var c;a in b&&(c=b[a],c=d.call(g,c,a,b),e[a]=c);a++}return e});

// Array.reduce polyfill (MDN)
"function"!==typeof Array.prototype.reduce&&(Array.prototype.reduce=function(d,e){if(null===this||"undefined"===typeof this)throw new TypeError("Array.prototype.reduce called on null or undefined");if("function"!==typeof d)throw new TypeError(d+" is not a function");var a=0,f=this.length>>>0,b,c=!1;1<arguments.length&&(b=e,c=!0);for(;f>a;++a)this.hasOwnProperty(a)&&(c?b=d(b,this[a],a,this):(b=this[a],c=!0));if(!c)throw new TypeError("Reduce of empty array with no initial value");return b});

// Function.bind polyfill (MDN)
Function.prototype.bind||(Function.prototype.bind=function(b){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var d=Array.prototype.slice.call(arguments,1),e=this,a=function(){},c=function(){return e.apply(this instanceof a&&b?this:b,d.concat(Array.prototype.slice.call(arguments)))};a.prototype=this.prototype;c.prototype=new a;return c});

// syringe-min.js v0.1.2
(function(){var h=this;h.syringe=function(j){var e={},d={},m={}.hasOwnProperty,n=[].slice,p=Object.prototype.toString,q=/^function\s*[^\(]*\(\s*([^\)]*)\)/m,r=/^\s*(_?)(\S+?)\1\s*$/,s=/((\/\/.*$)|(\/\*[\s\S]*?\*\/))/mg,f=function(a,c){var b=p.call(a).slice(8,-1);return c&&b.toLowerCase()||b},t=function(a,c,b){c=c||this;a=a.split(b||".");b=null;return b=a.filter(function(a){return a.length}).reduce(function(a,b,c,d){if(a)return a[d[c]]},c)},k=function(a,c,b){c=c||this;a=a.split(b||".");var g,d;g=0; for(d=a.length;g<d;g++)b=a[g],c=c[b]=c[b]||{};return c},u=function(a){return a.map(function(a){return d[a]},this)},l=function(){var a=n.call(arguments),c=a.shift(),b=c.toString().replace(s,"").match(q),b=u(b[1].split(",").map(function(a){return a.replace(r,function(a,b,c){return c})}));b.length-=a.length;return c.apply(this,b.concat(a))},d="object"===f(j,!0)?j:d;e.register=function(a,c){if("object"===f(a,!0)){for(var b in a)m.call(a,b)&&this.register.apply(this,[b,a[b]]);return this}d[a]=c;return this}; e.on=e.bind=function(a,c,b){if("string"===f(a,!0)&&"function"===f(c,!0)){b=b||h;a=a.split(".");var d=1<a.length?a.pop():!1;c=l.bind(b,c);if(d)k(a.join("."),b)[d]=c;else return b[a.join(".")]=c}else if("function"===f(a,!0))return b="object"===f(c,!0)?c:h,l.bind(b,a)};e.list=function(){return d};e.get=function(a){return t(a,d)};e.set=function(a,c){var b=a.split("."),e=1<b.length?b.pop():!1;e?k(b.join("."),d)[e]=c:d[b.toString()]=c;return this};e.remove=function(a){delete d[a];return this};return e}}).call(this);